// @generated by protobuf-ts 2.7.0 with parameter client_grpc1
// @generated from protobuf file "Events/InGame/ConcludeGameEvent.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ConcludeGameEventMsg
 */
export interface ConcludeGameEventMsg {
    /**
     * @generated from protobuf field: string doras = 1;
     */
    doras: string;
    /**
     * @generated from protobuf field: string uradoras = 2;
     */
    uradoras: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class ConcludeGameEventMsg$Type extends MessageType<ConcludeGameEventMsg> {
    constructor() {
        super("ConcludeGameEventMsg", [
            { no: 1, name: "doras", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "uradoras", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ConcludeGameEventMsg>): ConcludeGameEventMsg {
        const message = { doras: "", uradoras: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ConcludeGameEventMsg>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConcludeGameEventMsg): ConcludeGameEventMsg {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string doras */ 1:
                    message.doras = reader.string();
                    break;
                case /* string uradoras */ 2:
                    message.uradoras = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConcludeGameEventMsg, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string doras = 1; */
        if (message.doras !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.doras);
        /* string uradoras = 2; */
        if (message.uradoras !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uradoras);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ConcludeGameEventMsg
 */
export const ConcludeGameEventMsg = new ConcludeGameEventMsg$Type();
