// @generated by protobuf-ts 2.7.0 with parameter client_grpc1
// @generated from protobuf file "Events/InGame/DiscardTileEvent.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { TileSource } from "../../Core/GameTile";
import { DiscardReason } from "../../Core/GameTile";
import { GameTileMsg } from "../../Core/GameTile";
/**
 * @generated from protobuf message DiscardTileEventMsg
 */
export interface DiscardTileEventMsg {
    /**
     * @generated from protobuf field: int32 player_id = 1;
     */
    playerId: number;
    /**
     * @generated from protobuf field: GameTileMsg incoming = 2;
     */
    incoming?: GameTileMsg;
    /**
     * @generated from protobuf field: GameTileMsg discarded = 3;
     */
    discarded?: GameTileMsg;
    /**
     * @generated from protobuf field: DiscardReason reason = 4;
     */
    reason: DiscardReason;
    /**
     * @generated from protobuf field: TileSource origin = 5;
     */
    origin: TileSource;
    /**
     * @generated from protobuf field: bool is_riichi = 6;
     */
    isRiichi: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class DiscardTileEventMsg$Type extends MessageType<DiscardTileEventMsg> {
    constructor() {
        super("DiscardTileEventMsg", [
            { no: 1, name: "player_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "incoming", kind: "message", T: () => GameTileMsg },
            { no: 3, name: "discarded", kind: "message", T: () => GameTileMsg },
            { no: 4, name: "reason", kind: "enum", T: () => ["DiscardReason", DiscardReason, "DISCARD_REASON_"] },
            { no: 5, name: "origin", kind: "enum", T: () => ["TileSource", TileSource, "TILE_SOURCE_"] },
            { no: 6, name: "is_riichi", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DiscardTileEventMsg>): DiscardTileEventMsg {
        const message = { playerId: 0, reason: 0, origin: 0, isRiichi: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<DiscardTileEventMsg>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DiscardTileEventMsg): DiscardTileEventMsg {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 player_id */ 1:
                    message.playerId = reader.int32();
                    break;
                case /* GameTileMsg incoming */ 2:
                    message.incoming = GameTileMsg.internalBinaryRead(reader, reader.uint32(), options, message.incoming);
                    break;
                case /* GameTileMsg discarded */ 3:
                    message.discarded = GameTileMsg.internalBinaryRead(reader, reader.uint32(), options, message.discarded);
                    break;
                case /* DiscardReason reason */ 4:
                    message.reason = reader.int32();
                    break;
                case /* TileSource origin */ 5:
                    message.origin = reader.int32();
                    break;
                case /* bool is_riichi */ 6:
                    message.isRiichi = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DiscardTileEventMsg, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 player_id = 1; */
        if (message.playerId !== 0)
            writer.tag(1, WireType.Varint).int32(message.playerId);
        /* GameTileMsg incoming = 2; */
        if (message.incoming)
            GameTileMsg.internalBinaryWrite(message.incoming, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* GameTileMsg discarded = 3; */
        if (message.discarded)
            GameTileMsg.internalBinaryWrite(message.discarded, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* DiscardReason reason = 4; */
        if (message.reason !== 0)
            writer.tag(4, WireType.Varint).int32(message.reason);
        /* TileSource origin = 5; */
        if (message.origin !== 0)
            writer.tag(5, WireType.Varint).int32(message.origin);
        /* bool is_riichi = 6; */
        if (message.isRiichi !== false)
            writer.tag(6, WireType.Varint).bool(message.isRiichi);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message DiscardTileEventMsg
 */
export const DiscardTileEventMsg = new DiscardTileEventMsg$Type();
