// @generated by protobuf-ts 2.7.0 with parameter client_grpc1
// @generated from protobuf file "Server/Messages/Message.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ClientVersionCheckMsg } from "./VersionCheck";
import { ClientRoomUpdateMsg } from "./Room";
import { ClientInquiryMsg } from "./Inquiry";
import { ServerVersionCheckMsg } from "./VersionCheck";
import { ServerRoomStateMsg } from "./Room";
import { ServerPlayerStateMsg } from "./Room";
import { ServerInquiryEndMsg } from "./Inquiry";
import { ServerInquiryMsg } from "./Inquiry";
import { TwoWayHeartBeatMsg } from "./HeartBeat";
/**
 * @generated from protobuf message ServerMsg
 */
export interface ServerMsg {
    /**
     * @generated from protobuf oneof: msg
     */
    msg: {
        oneofKind: "heartBeatMsg";
        /**
         * @generated from protobuf field: TwoWayHeartBeatMsg heart_beat_msg = 1;
         */
        heartBeatMsg: TwoWayHeartBeatMsg;
    } | {
        oneofKind: "inquiryMsg";
        /**
         * @generated from protobuf field: ServerInquiryMsg inquiry_msg = 2;
         */
        inquiryMsg: ServerInquiryMsg;
    } | {
        oneofKind: "inquiryEndMsg";
        /**
         * @generated from protobuf field: ServerInquiryEndMsg inquiry_end_msg = 3;
         */
        inquiryEndMsg: ServerInquiryEndMsg;
    } | {
        oneofKind: "playerStateMsg";
        /**
         * @generated from protobuf field: ServerPlayerStateMsg player_state_msg = 4;
         */
        playerStateMsg: ServerPlayerStateMsg;
    } | {
        oneofKind: "roomStateMsg";
        /**
         * @generated from protobuf field: ServerRoomStateMsg room_state_msg = 5;
         */
        roomStateMsg: ServerRoomStateMsg;
    } | {
        oneofKind: "versionCheckMsg";
        /**
         * @generated from protobuf field: ServerVersionCheckMsg version_check_msg = 6;
         */
        versionCheckMsg: ServerVersionCheckMsg;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message ClientMsg
 */
export interface ClientMsg {
    /**
     * @generated from protobuf oneof: msg
     */
    msg: {
        oneofKind: "heartBeatMsg";
        /**
         * @generated from protobuf field: TwoWayHeartBeatMsg heart_beat_msg = 1;
         */
        heartBeatMsg: TwoWayHeartBeatMsg;
    } | {
        oneofKind: "inquiryMsg";
        /**
         * @generated from protobuf field: ClientInquiryMsg inquiry_msg = 2;
         */
        inquiryMsg: ClientInquiryMsg;
    } | {
        oneofKind: "roomUpdateMsg";
        /**
         * @generated from protobuf field: ClientRoomUpdateMsg room_update_msg = 3;
         */
        roomUpdateMsg: ClientRoomUpdateMsg;
    } | {
        oneofKind: "versionCheckMsg";
        /**
         * @generated from protobuf field: ClientVersionCheckMsg version_check_msg = 4;
         */
        versionCheckMsg: ClientVersionCheckMsg;
    } | {
        oneofKind: undefined;
    };
}
// @generated message type with reflection information, may provide speed optimized methods
class ServerMsg$Type extends MessageType<ServerMsg> {
    constructor() {
        super("ServerMsg", [
            { no: 1, name: "heart_beat_msg", kind: "message", oneof: "msg", T: () => TwoWayHeartBeatMsg },
            { no: 2, name: "inquiry_msg", kind: "message", oneof: "msg", T: () => ServerInquiryMsg },
            { no: 3, name: "inquiry_end_msg", kind: "message", oneof: "msg", T: () => ServerInquiryEndMsg },
            { no: 4, name: "player_state_msg", kind: "message", oneof: "msg", T: () => ServerPlayerStateMsg },
            { no: 5, name: "room_state_msg", kind: "message", oneof: "msg", T: () => ServerRoomStateMsg },
            { no: 6, name: "version_check_msg", kind: "message", oneof: "msg", T: () => ServerVersionCheckMsg }
        ]);
    }
    create(value?: PartialMessage<ServerMsg>): ServerMsg {
        const message = { msg: { oneofKind: undefined } };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ServerMsg>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ServerMsg): ServerMsg {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* TwoWayHeartBeatMsg heart_beat_msg */ 1:
                    message.msg = {
                        oneofKind: "heartBeatMsg",
                        heartBeatMsg: TwoWayHeartBeatMsg.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).heartBeatMsg)
                    };
                    break;
                case /* ServerInquiryMsg inquiry_msg */ 2:
                    message.msg = {
                        oneofKind: "inquiryMsg",
                        inquiryMsg: ServerInquiryMsg.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).inquiryMsg)
                    };
                    break;
                case /* ServerInquiryEndMsg inquiry_end_msg */ 3:
                    message.msg = {
                        oneofKind: "inquiryEndMsg",
                        inquiryEndMsg: ServerInquiryEndMsg.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).inquiryEndMsg)
                    };
                    break;
                case /* ServerPlayerStateMsg player_state_msg */ 4:
                    message.msg = {
                        oneofKind: "playerStateMsg",
                        playerStateMsg: ServerPlayerStateMsg.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).playerStateMsg)
                    };
                    break;
                case /* ServerRoomStateMsg room_state_msg */ 5:
                    message.msg = {
                        oneofKind: "roomStateMsg",
                        roomStateMsg: ServerRoomStateMsg.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).roomStateMsg)
                    };
                    break;
                case /* ServerVersionCheckMsg version_check_msg */ 6:
                    message.msg = {
                        oneofKind: "versionCheckMsg",
                        versionCheckMsg: ServerVersionCheckMsg.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).versionCheckMsg)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ServerMsg, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* TwoWayHeartBeatMsg heart_beat_msg = 1; */
        if (message.msg.oneofKind === "heartBeatMsg")
            TwoWayHeartBeatMsg.internalBinaryWrite(message.msg.heartBeatMsg, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* ServerInquiryMsg inquiry_msg = 2; */
        if (message.msg.oneofKind === "inquiryMsg")
            ServerInquiryMsg.internalBinaryWrite(message.msg.inquiryMsg, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* ServerInquiryEndMsg inquiry_end_msg = 3; */
        if (message.msg.oneofKind === "inquiryEndMsg")
            ServerInquiryEndMsg.internalBinaryWrite(message.msg.inquiryEndMsg, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* ServerPlayerStateMsg player_state_msg = 4; */
        if (message.msg.oneofKind === "playerStateMsg")
            ServerPlayerStateMsg.internalBinaryWrite(message.msg.playerStateMsg, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* ServerRoomStateMsg room_state_msg = 5; */
        if (message.msg.oneofKind === "roomStateMsg")
            ServerRoomStateMsg.internalBinaryWrite(message.msg.roomStateMsg, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* ServerVersionCheckMsg version_check_msg = 6; */
        if (message.msg.oneofKind === "versionCheckMsg")
            ServerVersionCheckMsg.internalBinaryWrite(message.msg.versionCheckMsg, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ServerMsg
 */
export const ServerMsg = new ServerMsg$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClientMsg$Type extends MessageType<ClientMsg> {
    constructor() {
        super("ClientMsg", [
            { no: 1, name: "heart_beat_msg", kind: "message", oneof: "msg", T: () => TwoWayHeartBeatMsg },
            { no: 2, name: "inquiry_msg", kind: "message", oneof: "msg", T: () => ClientInquiryMsg },
            { no: 3, name: "room_update_msg", kind: "message", oneof: "msg", T: () => ClientRoomUpdateMsg },
            { no: 4, name: "version_check_msg", kind: "message", oneof: "msg", T: () => ClientVersionCheckMsg }
        ]);
    }
    create(value?: PartialMessage<ClientMsg>): ClientMsg {
        const message = { msg: { oneofKind: undefined } };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ClientMsg>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ClientMsg): ClientMsg {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* TwoWayHeartBeatMsg heart_beat_msg */ 1:
                    message.msg = {
                        oneofKind: "heartBeatMsg",
                        heartBeatMsg: TwoWayHeartBeatMsg.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).heartBeatMsg)
                    };
                    break;
                case /* ClientInquiryMsg inquiry_msg */ 2:
                    message.msg = {
                        oneofKind: "inquiryMsg",
                        inquiryMsg: ClientInquiryMsg.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).inquiryMsg)
                    };
                    break;
                case /* ClientRoomUpdateMsg room_update_msg */ 3:
                    message.msg = {
                        oneofKind: "roomUpdateMsg",
                        roomUpdateMsg: ClientRoomUpdateMsg.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).roomUpdateMsg)
                    };
                    break;
                case /* ClientVersionCheckMsg version_check_msg */ 4:
                    message.msg = {
                        oneofKind: "versionCheckMsg",
                        versionCheckMsg: ClientVersionCheckMsg.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).versionCheckMsg)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ClientMsg, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* TwoWayHeartBeatMsg heart_beat_msg = 1; */
        if (message.msg.oneofKind === "heartBeatMsg")
            TwoWayHeartBeatMsg.internalBinaryWrite(message.msg.heartBeatMsg, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* ClientInquiryMsg inquiry_msg = 2; */
        if (message.msg.oneofKind === "inquiryMsg")
            ClientInquiryMsg.internalBinaryWrite(message.msg.inquiryMsg, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* ClientRoomUpdateMsg room_update_msg = 3; */
        if (message.msg.oneofKind === "roomUpdateMsg")
            ClientRoomUpdateMsg.internalBinaryWrite(message.msg.roomUpdateMsg, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* ClientVersionCheckMsg version_check_msg = 4; */
        if (message.msg.oneofKind === "versionCheckMsg")
            ClientVersionCheckMsg.internalBinaryWrite(message.msg.versionCheckMsg, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ClientMsg
 */
export const ClientMsg = new ClientMsg$Type();
