// @generated by protobuf-ts 2.7.0 with parameter client_grpc1
// @generated from protobuf file "Core/Player.proto" (syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum Wind
 */
export enum Wind {
    /**
     * @generated from protobuf enum value: WIND_E = 0;
     */
    WIND_E = 0,
    /**
     * @generated from protobuf enum value: WIND_S = 1;
     */
    WIND_S = 1,
    /**
     * @generated from protobuf enum value: WIND_W = 2;
     */
    WIND_W = 2,
    /**
     * @generated from protobuf enum value: WIND_N = 3;
     */
    WIND_N = 3
}
