// @generated by protobuf-ts 2.7.0 with parameter client_grpc1
// @generated from protobuf file "Server/Rpc/Info.proto" (syntax proto3)
// tslint:disable
import { InfoService } from "./Info";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { GetInfoResponse } from "./Info";
import type { Empty } from "../../google/protobuf/empty";
import * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service InfoService
 */
export interface IInfoServiceClient {
    /**
     * @generated from protobuf rpc: GetInfo(google.protobuf.Empty) returns (GetInfoResponse);
     */
    getInfo(input: Empty, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetInfoResponse) => void): grpc.ClientUnaryCall;
    getInfo(input: Empty, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetInfoResponse) => void): grpc.ClientUnaryCall;
    getInfo(input: Empty, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetInfoResponse) => void): grpc.ClientUnaryCall;
    getInfo(input: Empty, callback: (err: grpc.ServiceError | null, value?: GetInfoResponse) => void): grpc.ClientUnaryCall;
}
/**
 * @generated from protobuf service InfoService
 */
export class InfoServiceClient extends grpc.Client implements IInfoServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * @generated from protobuf rpc: GetInfo(google.protobuf.Empty) returns (GetInfoResponse);
     */
    getInfo(input: Empty, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetInfoResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetInfoResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetInfoResponse) => void)): grpc.ClientUnaryCall {
        const method = InfoService.methods[0];
        return this.makeUnaryRequest<Empty, GetInfoResponse>(`/${InfoService.typeName}/${method.name}`, (value: Empty): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetInfoResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
