// @generated by protobuf-ts 2.7.0 with parameter client_grpc1
// @generated from protobuf file "Actions/AgariAction.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message AgariActionMsg
 */
export interface AgariActionMsg {
    /**
     * @generated from protobuf field: AgariType type = 1;
     */
    type: AgariType;
}
/**
 * @generated from protobuf enum AgariType
 */
export enum AgariType {
    /**
     * None
     *
     * @generated from protobuf enum value: AGARI_TYPE_NONE = 0;
     */
    NONE = 0,
    /**
     * Ron
     *
     * @generated from protobuf enum value: AGARI_TYPE_RON = 1;
     */
    RON = 1,
    /**
     * Tsumo
     *
     * @generated from protobuf enum value: AGARI_TYPE_TSUMO = 2;
     */
    TSUMO = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class AgariActionMsg$Type extends MessageType<AgariActionMsg> {
    constructor() {
        super("AgariActionMsg", [
            { no: 1, name: "type", kind: "enum", T: () => ["AgariType", AgariType, "AGARI_TYPE_"] }
        ]);
    }
    create(value?: PartialMessage<AgariActionMsg>): AgariActionMsg {
        const message = { type: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<AgariActionMsg>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AgariActionMsg): AgariActionMsg {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* AgariType type */ 1:
                    message.type = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AgariActionMsg, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* AgariType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message AgariActionMsg
 */
export const AgariActionMsg = new AgariActionMsg$Type();
