// @generated by protobuf-ts 2.7.0
// @generated from protobuf file "Actions/KanAction.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { GameTilesMsg } from "../Core/GameTile";
/**
 * @generated from protobuf message KanActionMsg
 */
export interface KanActionMsg {
    /**
     * @generated from protobuf field: repeated GameTilesMsg tileGroups = 1;
     */
    tileGroups: GameTilesMsg[];
}
// @generated message type with reflection information, may provide speed optimized methods
class KanActionMsg$Type extends MessageType<KanActionMsg> {
    constructor() {
        super("KanActionMsg", [
            { no: 1, name: "tileGroups", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => GameTilesMsg }
        ]);
    }
    create(value?: PartialMessage<KanActionMsg>): KanActionMsg {
        const message = { tileGroups: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<KanActionMsg>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: KanActionMsg): KanActionMsg {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated GameTilesMsg tileGroups */ 1:
                    message.tileGroups.push(GameTilesMsg.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: KanActionMsg, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated GameTilesMsg tileGroups = 1; */
        for (let i = 0; i < message.tileGroups.length; i++)
            GameTilesMsg.internalBinaryWrite(message.tileGroups[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message KanActionMsg
 */
export const KanActionMsg = new KanActionMsg$Type();
