// @generated by protobuf-ts 2.7.0 with parameter client_grpc1
// @generated from protobuf file "Actions/PonAction.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { MenLikeMsg } from "../Core/MenLike";
/**
 * @generated from protobuf message PonActionMsg
 */
export interface PonActionMsg {
    /**
     * @generated from protobuf field: repeated MenLikeMsg tile_groups = 1;
     */
    tileGroups: MenLikeMsg[];
}
// @generated message type with reflection information, may provide speed optimized methods
class PonActionMsg$Type extends MessageType<PonActionMsg> {
    constructor() {
        super("PonActionMsg", [
            { no: 1, name: "tile_groups", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MenLikeMsg }
        ]);
    }
    create(value?: PartialMessage<PonActionMsg>): PonActionMsg {
        const message = { tileGroups: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PonActionMsg>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PonActionMsg): PonActionMsg {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated MenLikeMsg tile_groups */ 1:
                    message.tileGroups.push(MenLikeMsg.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PonActionMsg, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated MenLikeMsg tile_groups = 1; */
        for (let i = 0; i < message.tileGroups.length; i++)
            MenLikeMsg.internalBinaryWrite(message.tileGroups[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PonActionMsg
 */
export const PonActionMsg = new PonActionMsg$Type();
