// @generated by protobuf-ts 2.7.0 with parameter client_grpc1
// @generated from protobuf file "Actions/SkipAction.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message SkipActionMsg
 */
export interface SkipActionMsg {
}
// @generated message type with reflection information, may provide speed optimized methods
class SkipActionMsg$Type extends MessageType<SkipActionMsg> {
    constructor() {
        super("SkipActionMsg", []);
    }
    create(value?: PartialMessage<SkipActionMsg>): SkipActionMsg {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<SkipActionMsg>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SkipActionMsg): SkipActionMsg {
        return target ?? this.create();
    }
    internalBinaryWrite(message: SkipActionMsg, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message SkipActionMsg
 */
export const SkipActionMsg = new SkipActionMsg$Type();
