name: Code Generation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Protos/**'
  push:
    branches:
      - main
    paths:
      - 'Protos/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      
      - name: Install protobuf compiler
        run: sudo apt-get install protobuf-compiler protobuf-compiler-grpc

      - name: Correct GRPC plugin links
        run: sudo ln -s $(which grpc_csharp_plugin) /usr/bin/protoc-gen-csharp-grpc

      - name: NPM install
        run: npm install

      - name: Generate C# Code
        run: |
          rm -rf ./CS/
          mkdir ./CS/
          protoc --proto_path=./Protos/ --csharp_out=./CS/ --csharp-grpc_out=./CS/Server/Generated/Rpc/ --csharp_opt=base_namespace=RabiRiichi $(find ./Protos/ -iname "*.proto")

      - name: Generate TypeScript Code
        run: |
          rm -rf ./TS/
          mkdir ./TS/
          protoc --plugin=./node_modules/.bin/protoc-gen-ts --proto_path=./Protos/ --ts_out=./TS/ --ts_opt=client_grpc1 $(find ./Protos/ -iname "*.proto")

      - name: Commit files
        run: |
          git config --local user.email "411937015@qq.com"
          git config --local user.name "GitHub Action"
          git config --local core.autocrlf input
          git add --all
          git commit -m "Automated ProtoBuf Code Generation" -a --allow-empty
          
      - name: Push changes to github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref || github.ref }}
